ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- protolude
- text

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- LambdaCase
- PartialTypeSignatures
- RecordWildCards

executables:
  duckbot-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N