ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- protolude
- lens
- text
- mtl
- unordered-containers

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- LambdaCase
- PartialTypeSignatures
- RecordWildCards
- TemplateHaskell

executables:
  advent-of-code:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N